# Python Real-World Projects
# Project 1.1: Data Acquisition Base Application

[build-system]
requires = ["setuptools", "wheel"]  # PEP 508 specifications.

[project]
name = "project_1_1"
version = "1.0.0"
authors = [
    {name = "Author", email = "author@email.com"},
]
description = "Real-World Python Projects -- Project 1.1."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
]
dependencies = [
    # Packages this project requires
    "behave==1.2.6",
    "cachetools==5.3.1",
    "chardet==5.2.0",
    "colorama==0.4.6",
    "distlib==0.3.7",
    "filelock==3.12.2",
    "iniconfig==2.0.0",
    "isort>=8.0.1",
    "packaging==23.1",
    "parse==1.19.0",
    "parse-type==0.6.0",
    "platformdirs==3.10.0",
    "pluggy==1.2.0",
    "pyproject-api==1.5.4",
    "pytest==7.4.0",
    "six==1.16.0",
    "tox==4.9.0",
    "virtualenv==20.24.3",
]
[project.optional-dependencies]
dev = [
    # Development tools to work on this project
    "sphinx==7.2.2",
    "sphinxcontrib-plantuml==0.25",
    "pip-tools==7.3.0"
]
test = [
    # Testing tools to test this project
    "pytest==7.4.0",
    "tox==4.9.0",
    "behave==1.2.6"
]
